---
# Repo
- name: Install Rpmfusion Free repos
  dnf:
    name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
    state: present
  become: true

- name: Install Rpmfusion NonFree repos
  dnf:
    name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
    state: present
  become: true

- name: Install Adobe repos
  dnf:
    name: http://linuxdownload.adobe.com/adobe-release/adobe-release-x86_64-1.0-1.noarch.rpm
    state: present
  become: true

- name: Enable eminguez repo
  command: dnf copr enable -y eminguez/eminguez-RPMs
  become: true

- name: Enable fedora-cisco-openh264
  command: dnf config-manager --set-enabled fedora-cisco-openh264
  become: true

- name: Enable kcli repo
  command: dnf copr enable -y karmab/kcli
  become: true
