---
- name: All roles
  hosts: localhost
  gather_facts: yes
  roles:
    - repos
    - dropbox
    - atom
    - bluejeans
    - chrome
    - firefox
    - golang
    - msttcorefonts
    - paper-icons
    - spotify
    - multimedia
    - packages
    - misc
    - gsettings
    - dotfiles
    - scripts
